### ISSUE TITLE
nodejs_npm resource not idempotent

### ISSUE THREAD

**Issue by rlafferty** [redguide/nodejs#183] opened 2017-08-01 19:44 UTC
### Cookbook version
4.0.0

### Chef-client version
Chef: 13.2.20

### Platform Details
Ubuntu-12.04

### Scenario:
```ruby
nodejs_npm 'gulp'
  version '3.9'
end
```
This will run every time.  Its failing the `url_valid?` method call in the [nodejs helpers library](https://github.com/redguide/nodejs/blob/master/libraries/nodejs_helper.rb#L28)

### Steps to Reproduce:
Install node from binary version `4.4.5`

```ruby
nodejs_npm 'gulp' do
  version '3.9'
end
```

run converge twice (will install each time).

### Expected Result:
In the `url_valid?` method in the nodejs helper library:
```ruby
list.fetch(package, {}).fetch('resolved', '').include?('url')
```
the `resolved` key does not contain a `url` key.

### Actual Result:
The output from `npm list gulp -global -json` is as follows:
```json
{
  "dependencies": {
    "gulp": {
      "version": "3.9.1",
      "from": "gulp@>=3.9.0 <3.10.0",
      "resolved": "https://registry.npmjs.org/gulp/-/gulp-3.9.1.tgz"
    }
  }
}
```

**Comment by stevenoneill** [comment] 2017-08-17 03:11
Diito with chef client 12.21 on RHEL 7.2.  Same scenario

**Comment by daften** [comment] 2017-09-26 21:45
Is a duplicate of #115 it seems ...

**Comment by tas50** [comment] 2017-11-15 17:05
New release will fix this

**Closed** 2017-11-15 17:05 UTC
